import { z } from "zod";
const githubUrl = z.string().url().refine((v) => { const u = new URL(v); const seg=u.pathname.split("/").filter(Boolean); return u.protocol === "https:" && u.hostname === "github.com" && !u.username && !u.password && !u.port && !u.search && !u.hash && !u.pathname.endsWith("/") && !seg.some((s)=>s==="."||s===".."); });
const utc = z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?Z$/).refine((v) => !Number.isNaN(Date.parse(v)));
const keys = ["releases", "authoredPullRequests", "mergedPullRequests", "reviews", "openedIssues", "closedIssues", "issueComments"] as const;
const literals = ["release", "authored_pull_request", "merged_pull_request", "review", "opened_issue", "closed_issue", "issue_comment"] as const;
const base = { id:z.string().min(1), actor:z.string().min(1), occurredAt:utc, url:githubUrl, title:z.string(), attributionRule:z.string().min(1) };
const item = (type: typeof literals[number]) => z.object({...base,type:z.literal(type)}).strict();
export const reportSchema = z.object({schemaVersion:z.literal("1.0"),generatedAt:utc,status:z.enum(["complete","partial"]),query:z.object({repository:z.object({owner:z.string().min(1),name:z.string().min(1),fullName:z.string().min(3)}).strict(),maintainer:z.string().min(1),since:utc,until:utc,maxItems:z.number().int().positive().max(1000)}).strict(),repository:z.object({owner:z.string().min(1),name:z.string().min(1),fullName:z.string().min(3),description:z.string().nullable(),sourceUrl:githubUrl,observedAt:utc}).strict(),activities:z.object(Object.fromEntries(keys.map((k,i)=>[k,z.array(item(literals[i]))])) as never).strict(),summary:z.object(Object.fromEntries([...keys.map(k=>[k,z.number().int().nonnegative()]),["total",z.number().int().nonnegative()]]) as never).strict(),community:z.record(z.string(),z.discriminatedUnion("status",[z.object({status:z.literal("present"),sourceUrl:githubUrl}).strict(),z.object({status:z.literal("absent"),sourceUrl:githubUrl.nullable().optional()}).strict(),z.object({status:z.literal("unavailable"),sourceUrl:githubUrl.nullable().optional()}).strict()])),adoption:z.object({stars:z.number().int().nonnegative().nullable(),forks:z.number().int().nonnegative().nullable(),watchers:z.number().int().nonnegative().nullable(),observedAt:utc.nullable()}).strict(),pagination:z.object(Object.fromEntries(keys.map(k=>[k,z.object({fetched:z.number().int().nonnegative(),truncated:z.boolean()}).strict()])) as never).strict(),limitations:z.array(z.object({code:z.string().min(1),resource:z.string().min(1),message:z.string().min(1)}).strict())}).strict();
export type Report = z.infer<typeof reportSchema>;
